name: Frontend CI

on:
  push:
    branches:
      - main
      - docker-images # test
  pull_request:
    branches:
      - main
      - docker-images # test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.9

    - name: Install Dependencies
      run: |
        cd Frontend/hypno-buddy
        npm install

    - name: Build Vite
      run: |
        cd Frontend/hypno-buddy
        npm run vite-build